name: Publish tagged releases to jsr.io

on:
  push:
    tags:
      - "release/*"

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v1
        with:
          deno-version: vx.x.x
      - run: deno publish
